env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
  - prettier
  - 'react-app'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'eslint-plugin-prettier'
rules:
  {
    'prettier/prettier': 'error',
    'react/jsx-filename-extension':
      ['warn', { extensions: ['.js', '.jsx', '.tsx'] }],
    'import/prefer-default-export': 'off',
    'jsx-quotes': ['error', 'prefer-single'],
    'camelcase': 'off',
    'react/prop-types': 'off',
  }
